name: Build and deploy mkdocs to github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip       # install pip
          python3 -m pip install -r requirements.txt # install requirements.txt
      - name: Run parse_yaml_files.py
        run: python3 parse_yaml_files
      - name: Run test
        run: python3 tests/test_outputs.py
